import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import {connectDB} from './config/db.js';
import authRoutes from './routes/auth.js';
import linkRoutes from './routes/links.js';
import bioRoutes from './routes/bio.js';
import {redirect,} from './controllers/linkController.js';
import {redirectLimiter} from './middleware/rateLimit.js';
import {notFound,errorHandler} from './middleware/error.js';
const app=express();
app.set('trust proxy',1);app.use(helmet());app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173',credentials:true}));app.use(express.json({limit:'1mb'}));app.use(cookieParser());
app.get('/health',(req,res)=>res.json({status:'ok',service:'branded-shortlink-api'}));
app.use('/api/auth',authRoutes);app.use('/api/links',linkRoutes);app.use('/api/bio',bioRoutes);app.get('/r/:shortCode',redirectLimiter,redirect);
app.use(notFound);app.use(errorHandler);
const port=process.env.PORT||5000;
connectDB(process.env.MONGODB_URI).then(()=>app.listen(port,()=>console.log(`API listening on ${port}`))).catch(err=>{console.error(err);process.exit(1)});
